[tool.poetry]
name = "rl_recsys"
version = "0.1.0"
description = ""
authors = ["Asr419 <aayush.singha.roy@iitd.ac.in>"]

[tool.poetry.dependencies]
python = "^3.9"
jupyter = "^1.0.0"
pandas = "^1.5.1"
numpy = "^1.23.4"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
