name: run_simulation
program: run_simulation.py
parameters:
  ######## User related parameters ########
  resp_amp_factor:
    value: 1.0
  satisfaction_threshold:
    value: 0.5
  state_update_rate:
    value: 0.99
  state_model_cls:
    value: AlphaIntentUserState
  choice_model_cls:
    value: DotProductChoiceModel
  response_model_cls:
    value: DotProductResponseModel
  ######## Environment related parameters ########
  num_users:
    value: 100
  slate_size:
    value: 5
  num_item_features:
    value: 14
  num_candidates:
    value: 1000
  retrieval_model:
    value: cosine
  ######## Training related parameters ########
  batch_size:
    value: 8
  gamma:
    value: 1.0
  tau:
    value: 0.01
  lr:
    value: 1e-4
  num_episodes:
    value: 1000
  ######## Models related parameters ########
  model:
    value: SlateQ_Cosine
  history_model_cls:
    value: LastObservationModel
  slate_gen_model_cls:
    value: TopKSlateGenerator
  intent_kind:
    value: "observable"
  hist_length:
    value: 5
  
#reproducibility
  seed: 
    value: 20202
  working_model:
    value: "TopK_random"