name: run_simulation
program: run_simulation.py
parameters:
  ######## User related parameters ########
  resp_amp_factor:
    value: 10.0
  satisfaction_threshold:
    value: 0.7
  state_update_rate:
    value: 0.9  
  state_model_cls:
    value: AlphaIntentUserState
  choice_model_cls:
    value: CosineSimilarityChoiceModel
  response_model_cls:
    value: CosineResponseModel
  ######## Environment related parameters ########
  num_users:
    value: 500
  slate_size:
    value: 5
  num_item_features:
    value: 14
  num_candidates:
    value: 100
  retrieval_model:
    value: cosine
  ######## Training related parameters ########
  batch_size:
    value: 128
  gamma:
    value: 1.0
  tau:
    value: 0.001
  lr:
    value: 1e-4
  num_episodes:
    value: 1600
  ######## Models related parameters ########
  model:
    value: SlateQ_Cosine
  history_model_cls:
    value: AvgHistoryModel
  slate_gen_model_cls:
    value: TopKSlateGenerator
  intent_kind:
    value: "observable"
  hist_length:
    value: 5
  
#reproducibility
  seed: 
    value: 3005