name: run_simulation
program: run_simulation.py
parameters:
  batch_size:
    value: 128
  gamma:
    value: 1.0
  tau:
    value: 0.001
  lr:
    value: 1e-5
  num_episodes:
    value: 1500
  slate_size:
    value: 10
  num_item_features:
    value: 14
  num_candidates:
    value: 200
  num_users:
    value: 500
  timing:
    value: False
  state_model_cls:
    value: AlphaIntentUserState
  choice_model_cls:
    value: CosineSimilarityChoiceModel
  response_model_cls:
    value: CosineResponseModel
  choice_model:
    value: CosineSimilarityChoiceModel