name: run_simulation
program: run_simulation.py
parameters:
  ######## User related parameters ########
  resp_amp_factor:
    value: 1.0
  state_update_rate:
    value: 0.95
  state_model_cls:
    value: AlphaIntentUserState
  choice_model_cls:
    value: DotProductChoiceModel
  response_model_cls:
    value: DotProductResponseModel
  ######## Environment related parameters ########
  num_users:
    value: 100
  song_per_session:
    value: 30
  slate_size:
    value: 5
  num_item_features:
    value: 14
  num_candidates:
    value: 1000
  ######## Training related parameters ########
  batch_size:
    value: 32
  gamma:
    value: 1.0
  tau:
    value: 0.01
  lr:
    value: 5e-4
  num_episodes:
    value: 1000
  device:
    value: "gpu"
  ######## Models related parameters ########
  history_model_cls:
    value: LastObservationModel
  belief_model_cls:
    value: NNBeliefModel
  slate_gen_model_cls:
    value: TopKSlateGenerator
  hist_length:
    value: 10
  intent_kind:
    value: "hidden"
  ######## Wolpertinger policy ########
  nearest_neighbours:
    value: 50
  ######## Seed ########
  seeds: 
    value: [2,3,5,7,11]
  ######## Grouping ########
  grouping:
    value: "TopK_hidden"
  